- name: Synapse workspace deployment
  uses: Azure/Synapse-workspace-deployment@V1.7.0
  with:
    # Provide the Synapse workspace name where you want to deploy the artifacts.
    TargetWorkspaceName: 
    # Specify the path to the workspace artifacts template.
    TemplateFile: 
    # Specify the path to the template parameter file.
    ParametersFile: 
    # Specify deployment parameter values.
    OverrideArmParameters: # optional, default is 
    # Provide the type of cloud environment. Valid values are: Azure Public, Azure China, Azure US Government, Azure Germany
    Environment: 
    # Provide the resource group of the target Synapse workspace.
    resourceGroup: 
    # Provide client id of service principal.
    clientId: # optional
    # Provide client secret of the service principal.
    clientSecret: # optional
    # Provide subscription id.
    subscriptionId: 
    # Provide tenant id.
    tenantId: # optional
    # Delete the artifacts which are in the workspace but not in the template.
    DeleteArtifactsNotInTemplate: # optional
    # Use managed identity to generate the bearer token?
    managedIdentity: # optional
    # Deploy managed private endpoints in the template.
    deployManagedPrivateEndpoint: # optional
    # Mark the pipeline as failed if ARM overrides are missing.
    FailOnMissingOverrides: # optional
    # Provide path to the root folder.
    ArtifactsFolder: # optional
    # Provide name of the operation.
    operation: 
    # Source for the npm package. Only for dev testing.
    npmpackage: # optional
